spring:
  application:
    name: my-sample-board
    
---

server:
  port: 8080

---

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
---

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

---

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

      
#logging:
#  level:
#    org:
#      springframework:
#        web:
#          servlet: DEBUG
#    
