spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
    
  sql:
    init:
      mode: never

---

server:
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: -1
 
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      location: /tmp/upload
      
---

file:
  upload:
    dir: ${FILE_UPLOAD_DIR:C:/workspace/files/}

    
---

jwt:
  secret:
    key: ${JWT_SECRET_KEY:eW91c2h1b2xkZ29hbmRsb3ZleW91cnNlbGZqdXN0aW5iaWViZXI=}