CREATE TABLE t_board_user
(
   id VARCHAR2 (36) PRIMARY KEY,
   email VARCHAR2 (100) NOT NULL UNIQUE,
   password VARCHAR2 (255) NOT NULL,
   name VARCHAR2 (100) NOT NULL UNIQUE,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);